sfs_auth/urls.py
from django.urls import path

from . import views

app_name='auth'
urlpatterns = [
	path('register/', views.register, name='register'),
	path('login/', views.user_login, name='login' ),
	path('logout/', views.user_logout, name = 'logout'),
]

sfs_main/urls.py
from django.urls import path

from . import views

# Note: this app_name does NOT exactly match the actual name of the module!
# (main vs. sfs_main)
# It may be better to have them match for consistency... I'm not sure what
# the best practice is. For an initial attempt, I think it might be nice to
# be able to type "main/home" instead of "sfs_main/home" all over the place.
app_name='main'
urlpatterns = [
	path('', views.home, name='home'),
]

sfs_upload/urls.py
from django.urls import path

from . import views

app_name='upload'
urlpatterns = [
	path('', views.file, name='file'),
	path('upload', views.upload, name='upload'),
]

simple_file_share/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('sfs_auth.urls')),
    path('files/', include('sfs_upload.urls')),
    path('', include('sfs_main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# the `static(...)` function appended to the urlpatterns array configures
# the django development server to serve files from the Media_Root
# *on the development server only*; this setting has no effect otherwise

sfs_auth/models.py
from django.db import models
from .forms import (RegistrationForm)

# Create your models here.
class FileShareUsers(models.Model):

    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    username = models.CharField(max_length=50, primary_key=True)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=500)

    def __str__(self):
        return self.username

sfs_main/models.py
from django.db import models

# Create your models here.

sfs_upload/models.py
from django.db import models
from django.contrib.auth.models import User, AnonymousUser

def generateFilepath(instance, filename):
	# will store the upload in MEDIA_ROOT/uploads/<userid>/<id>-<filename>
	return 'uploads/{0}/{1}-{2}'.format(instance.user.id, instance.id, filename)

# Create your models here.
class Document(models.Model):
	# the date and time the file was uploaded
	uploaded_at = models.DateTimeField(auto_now_add=True)
	# the user who uploaded the file - I'd rather not allow nulls, but it was
	# necessary for the automatic migration to work
	user = models.ForeignKey(User, models.CASCADE, null=True)
	# a user-provided description of the file (defaults to blank)
	description = models.TextField(max_length=600, blank=True)
	# the file that was uploaded
	document = models.FileField(upload_to='documents/')

sfs_auth/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


#class UploadFileForm(forms.Form):
#    title = forms.CharField(max_length=100)
#    file = forms.FielField()
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

#class ViewandChooseFiles()
#   conn = sqlite.connect('database file name')
#   cur = conn.cursor()
#   cur.execute('SELECT * FROM files')
#   for row in cursor:
#       print 'File:', row[0]
#        print 'FileName:', row[1]
#

class RegistrationForm(UserCreationForm):
    username = forms.CharField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        )
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

sfs_upload/forms.py
from django import forms
from sfs_upload.models import Document

class DocumentForm(forms.ModelForm):
	class Meta:
		model = Document
		fields = ('description', 'document',)

sfs_auth/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import (RegistrationForm, LoginForm)

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    request.session.set_expiry(86400)
                    login(request,user)
                    return HttpResponseRedirect(reverse('main:home'))
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
        # TODO: have these^ return the login page with a modified context indicating the error!
    else:
        form = LoginForm()
        args = {'form': form}
    return render(request, 'sfs_auth/login.html',args)

#-------------------------------------------------
#The user_logout function will handle the log out
# functionality and render the logged out message
#------------------------------------------------
def user_logout(request):
    logout(request)
    return redirect('main:home')

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'sfs_auth/register.html', args)

sfs_main/views.py
from django.shortcuts import render
from django.contrib.auth import get_user
from sfs_upload.models import Document

# global home page
def home(request):
	user=get_user(request)
	if user.is_authenticated:
		files = Document.objects.order_by('-uploaded_at').filter(user__id__exact=user.id)
		return render(request, 'sfs_main/dashboard.html', {'files': files})
	else:
		return render(request, 'sfs_main/welcome.html')

sfs_upload/views.py
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from .forms import DocumentForm
from .models import Document

# View uploaded files
@login_required(login_url=reverse_lazy('auth:login'))
def file(request):
	documents = Document.objects.all()
	return render(request, 'sfs_upload/files.html', {'documents': documents})

@login_required(login_url=reverse_lazy('auth:login'))
def upload(request):
	if request.method == 'POST':
		form = DocumentForm(request.POST, request.FILES)
		if form.is_valid():
			# as a shortcut, could call form.save() here and be done,
			# but we'll create the model instance manually so that
			# we can inject the user who uploaded the document
			document = Document(
				user = request.user,
				description = request.POST['description'],
				document = request.FILES['document']
				)
			document.save()
			# if the document was saved, go to the "main" upload page so
			# we can see what was uploaded
			return redirect('main:home')
	else:
		form = DocumentForm()
	return render(request, 'sfs_upload/model_form_upload.html', {'form': form})

sfs_auth/templates/sfs_auth/login.html
{% extends 'base/layout.html' %}
{% block title %} Log - in{% endblock %}
{% block content %}

    <div id="container" >
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <div class="panel">
                    <div class="panel-heading custom-header-panel">
                        <h3 class="panel-title roboto">Log-in</h3>
                    </div>
                    <div class="panel-body">
                        <form action="{% url 'auth:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                        <label class="col-sm-4 control-label" for="name">Username <span class="requerido"> *</span></label>
                                        <div class="col-sm-8">
                                            {{ form.username }}
                                        </div>
                                </div>
                                <div class="form-group">
                                            <label class="col-sm-4 control-label" for="name">Password <span class="requerido"> *</span></label>
                                            <div class="col-sm-8">
                                                {{ form.password }}
                                            </div>
                                </div>

                                <div class="form-group text-center">
                                            <button type="submit" id="submit_btn" class="btn btn-blue-md roboto">Log in</button>
                                </div>

                        </form>
                            <p class="change_link">
                                    Not a member yet ?
                                    <a href="{% url 'auth:register'  %}">Register Here</a>
                            </p>
                    </div>
                </div>
            </div>
        </div>

</div> <!-- /form -->
{% endblock %}

sfs_auth/templates/sfs_auth/register.html
{% extends 'base/layout.html' %}
{% block title %} Log - in{% endblock %}
{% block content %}

    <div id="container" >
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <div class="panel">
                    <div class="panel-heading custom-header-panel">
                        <h3 class="panel-title roboto">Register</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                        <label class="col-sm-4 control-label" for="name">First Name <span class="requerido"> *</span></label>
                                        <div class="col-sm-8">
                                            {{ form.first_name }}
                                        </div>
                                </div>
                                <div class="form-group">
                                        <label class="col-sm-4 control-label" for="name">Last Name <span class="requerido"> *</span></label>
                                        <div class="col-sm-8">
                                            {{ form.last_name }}
                                        </div>
                                </div>
                                <div class="form-group">
                                        <label class="col-sm-4 control-label" for="name">Username <span class="requerido"> *</span></label>
                                        <div class="col-sm-8">
                                            {{ form.username }}
                                        </div>
                                </div>
                                <div class="form-group">
                                            <label class="col-sm-4 control-label" for="name">Password<span class="requerido"> *</span></label>
                                            <div class="col-sm-8">
                                                {{ form.password1 }}
                                            </div>
                                </div>

                                <div class="form-group">
                                        <label class="col-sm-4 control-label" for="name">Password Confirmation<span class="requerido"> *</span></label>
                                        <div class="col-sm-8">
                                            {{ form.password2 }}
                                        </div>
                            </div>

                                <div class="form-group text-center">
                                            <button type="submit" id="submit_btn" class="btn btn-blue-md roboto">Register</button>
                                </div>

                        </form>
                            <p class="change_link">
                                    Already a member ?
                                    <a href="{% url 'auth:login'  %}">Register Here</a>
                            </p>
                    </div>
                </div>
            </div>
        </div>

</div> <!-- /form -->
{% endblock %}

sfs_auth/templates/sfs_auth/viewfiles.html
<!DOCTYPE html>
<html lang="en">

<head>    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />    
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../assets/css/light-bootstrap-dashboard.css?v=2.0.1" rel="stylesheet" />

</head>

<body>
	
    <div class="wrapper">
        <div class="sidebar" data-image="../assets/img/sidebar-5.jpg">

            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li>
                        <a href="fileupload.html" id="uploadLink">        
                            Upload a File
                        </a>
                    </li>
                    <li>
                        <a id="viewFiles" href="viewfiles.html">                            
                            <p>View Files</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class=" container-fluid  ">
                    <a class="navbar-brand" href="#pablo"> Djano - File - Share </a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item">
                                
                            </li>
                            <li class="dropdown nav-item">
                                
                            </li>
                            <li class="nav-item">
                                
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href=" ">
                                    <span class="no-icon">% un=sfs_auth.models._str_(); print "Welcome "; print un %</span>
                                </a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link" href="dashboard.py" value="logout" name="LogOut">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content" id="section">
                <div class="container-fluid">
                    <div>
					
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container">
                    <nav>
                        <ul class="footer-menu">
                            <li></li><li></li><li></li><li></li>      
                            
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            Ninja Pirates, Test Site
                        </p>
                    </nav>
                </div>
            </footer>
        </div>
    </div>
    
</body>
<!--   Core JS Files   -->
<script src="../assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="../assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="../assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="../assets/js/plugins/bootstrap-switch.js"></script>
</html>

sfs_main/templates/sfs_main/dashboard.html
{% extends 'base/layout-loggedin.html' %}
{% block title %}SFS | My Files{% endblock %}

{% block header %}My Files{% endblock %}

{% block content %}

{% if files %}
	{% for f in files %}
	<div class="card">
		<div class="card-header">
			<h4 class="card-title">
				{{ f.document.name }}
			</h4>
			<p class="card-category">
				{{ f.user.username }}
			</p>
		</div>
		<div class="card-body">
			<p>
				<a href="{{ f.document.url }}">
					{{ f.document.url }}	
				</a>
			</p>
			<p>
				{{ f.description }}
			</p>
		</div>
		<div class="card-footer">
			<hr/>
			<div class="stats">
				<i class="fa fa-clock-o"></i>
				{{ f.uploaded_at }}
			</div>
		</div>
	</div>
	{% endfor%}
{% else %}
	<p>
		You haven't uploaded anything yet. Why not <a href="{% url 'upload:upload' %}">upload a file</a>, or have a look at <a href="{% url 'upload:file' %}">what other people have uploaded</a>?
	</p>
{% endif %}

{% endblock %}

sfs_main/templates/sfs_main/welcome.html
{% extends 'base/layout.html' %}
{% block title %} Home {% endblock %}

{% block content %}

    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1>Welcome to SFS</h1>

        <p class="lead">Share files With others. Find what you are looking by loging in if you have an account <a href="{% url 'auth:login' %}">Log-in</a> or register <a href="{% url 'auth:register' %}">Register</a> if you don't have an account.</p>
    </div>
  </div>
{% endblock %}

sfs_upload/templates/sfs_upload/files.html
{% extends 'base/layout-loggedin.html' %}

{% block title %}SFS | Downloads{% endblock %}
{% block header %}Downloads{% endblock %}

{% block content %}

    <h3>Available Downloads</h2>
    {% if documents %}
    <ul>
    {% for obj in documents %}
      <li>
        <a href="{{ obj.document.url }}">{{ obj.document.name }}</a> |<a href="{{ obj.document.url }}" download> Download</a>

      </li>
    {% endfor %}
    </ul>
    {% else %}
        <p> No documents</p>
    {% endif %}

{% endblock %}

{% block javascript%}
{%endblock%}

sfs_upload/templates/sfs_upload/model_form_upload.html
{% extends 'base/layout-loggedin.html' %}
{% block title %} SFS | Upload {% endblock %}
{% block header %}Upload a file{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
    	{% csrf_token %}
    	{{ form.as_p }}
    	<button type="submit">Upload</button>
	</form>

	<p>
		<a href="{% url 'upload:file' %}">Back to files</a>
	</p>

{% endblock %}

{% block javascript%}
{%endblock%}

templates/base/layout-loggedin.html
<!DOCTYPE html>
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    
    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    
    <!-- CSS Files -->
    <link href="{% static 'css/bootstrap-dashboard.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/light-bootstrap-dashboard.css' %}" rel="stylesheet" />
    <link href="{% static 'css/pe-icon-7-stroke.css' %}" rel="stylesheet" />
    
    <title>{% block title %}SFS{% endblock %}</title>
</head>
<body>
    <div class="wrapper">
        
        <div class="sidebar" data-color="purple" data-image="{% static 'img/sidebar.jpg' %}">

            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="{% url 'main:home' %}" class="simple-text">FILE SHARING HUB</a>
                </div>

                {% block sidebar %}
                <ul class="nav">
                    <li class="active">
                        <a href="{% url 'main:home'%}">
                            <p style="color:white"><i class="pe-7s-user"></i> My Files</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'upload:upload'%} ">
                            <p style="color:white"><i class="pe-7s-cloud-upload"></i> Upload a File</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'upload:file' %}">
                            <p style="color:white"><i class="pe-7s-users"></i> View Other Files</p>
                        </a>
                    </li>
                </ul>
                {% endblock %}

        	</div>
        </div><!--/sidebar-->

        <div class="main-panel">
            
            {% block nav %}
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                    <a class="navbar-brand" href="">{% block header %}{% endblock%}</a>
                    <button href="" 
                        class="navbar-toggler navbar-toggler-right" 
                        type="button" 
                        data-toggle="collapse" 
                        aria-controls="navigation-index" 
                        aria-expanded="false" 
                        aria-label="Toggle navigation">
                        
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item">
                                
                            </li>
                            <li class="dropdown nav-item">
                                
                            </li>
                            <li class="nav-item">
                                
                            </li>
                        </ul>
                        <!-- right side -->
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:home' %}">
                                    <span class="no-icon">Welcome {{ user.username }}!</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auth:logout' %}">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% endblock %}
            <!-- End Navbar -->
            
            <div class="content" id="section">
                <div class="container-fluid">
                        {% block content %}{% endblock %}
                </div>
            </div>

            {% block footer %}
            <footer class="footer">
                <div class="container">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a class="nav-link" href="{% url 'admin:index' %}">
                                    <span class="no-icon">Admin Login</span>
                                </a>
                            </li><li></li><li></li><li></li>
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            Ninja Pirates, Test Site
                        </p>
                    </nav>
                </div>
            </footer>
            {% endblock %}
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="{% static 'js/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap-dashboard.min.js' %}" type="text/javascript"></script>
    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script src="{% static 'js/bootstrap-switch.js' %}" type="text/javascript"></script>
    <!-- Control Center for Light Bootstrap Dashboard -->
    <script src="{% static 'js/light-bootstrap-dashboard.js' %}" type="text/javascript"></script>
    {% block javascript %}
    {% endblock %}
</body>

templates/base/layout.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %}SFS{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "mystyle.css"%}" rel="stylesheet">
    
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    {% block nav %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:home' %}">Simple File Share</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                
                <ul class="nav navbar-nav navbar-right">
                    
                    {% if user.is_authenticated %}
                    
                    <li>
                        <a href="">{{ user.username }}</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{% url 'main:home' %}">Upload File</a>
                            </li>
                            <li>
                                <a href="">View Files</a>
                            </li>
                            <li>
                                <a href="#">View Download Stats</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="#">View Profile</a>
                            </li>
                            <li class="divider"></li>

                            <li>
                                <a href="{% url 'auth:logout' %}">Logout</a>
                            </li>
                        </ul>
                    </li>
                            
                    {% else %}
                    
                    <li>
                        <a href="{% url 'auth:login' %}">Log-in</a>
                    </li>
                    <li>
                        <a href="{% url 'auth:register' %}">Register</a>
                    </li>
                    
                    {%endif%}

                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}

    <div class="container">

        {% block content %}

        {% endblock %}

    </div>
    


    <div class="container">

    {% block footer %}
        <footer class="footer">
            <div class="container">
                <nav>
                    <ul class="footer-menu"></ul>
                    <p class="copyright text-center">
                        ©
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        Ninja Pirates, Test Site
                    </p>
                </nav>
            </div>
        </footer>
    {% endblock %}
    
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src = "{% static 'js/jquery.min.js' %}"></script>
    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
    
    {% block javascript %}
    {% endblock %}
</body>
</html>